// GENERATED page blurbs — what the Sutradhar says about each page.
// Written by actually reading the printed pages (English/Hindi/Marathi).
export const pageBlurbs = {
 "p045.jpg": "Jayachandra Vandanapu of SY-IT opens with 'From Nukes to Navigation', tracing how Cold War dread — Sputnik, ARPANET, missile mathematics — quietly gifted us GPS and the internet, the everyday marvels born so a message could survive the end of the world.",
 "p046.jpg": "In 'Unapologetically Me', Sampada Tagalpallewar of BE-IT reflects on patience when plans go politely ignored by the universe — how tough phases don't remake us but reveal us, and how quiet confidence means staying yourself while the timing catches up.",
 "p047.jpg": "Vaidehi Mahale of TE E&TC confesses in 'One Text. Two Hours. 67 Reels.' how a single reply dissolved into an evening of scrolling — a warm, funny meditation on popcorn brain, jumpy attention, and why your mind isn't broken, just popped.",
 "p048.jpg": "In 'A Letter to My Younger Self', Ameya Pravin Surve of SE-IT writes tenderly in verse to the boy he was — warning that storms visit even the disciplined, that finish lines drift, and that becoming, not perfection, was always the point.",
 "p049.jpg": "Nisarga Kadam of FY-E&TC pours heartbreak through Naruto's world in 'A Love Like Fire and Wind' — a poem of chasing like fire, waiting like Obito, and finally learning, as Naruto did, that some battles are never meant to be won.",
 "p050.jpg": "'From Cave Walls to Digital Pixels' begins a sweeping journey through art's history — from a 45,500-year-old Sulawesi pig painting and Bhimbetka's ochre hunters to Ellora's carved temples and the Six Limbs of Indian painting, where instinct became discipline.",
 "p051.jpg": "The story continues as paper, printmaking, and photography give way to pixels and AI. Aditya Deshpande and Shrawani Choukone ask whether code can ever carry the ache of memory, concluding that the human instinct to create endures every transformation.",
 "p052.jpg": "'Journey Across States' opens in Delhi's bustling Janpath market, where a boy briefly loses his mother, then watches her haggle a vendor down with theatrical flair — a warm beginning to one family's story of belonging across India's cities.",
 "p053.jpg": "The story continues from Delhi's Paranthe Wali Gali to a nervous first flight toward Kolkata, the City of Joy — where COVID lockdowns, Victorian streets, College Street's Coffee House, and six slow years turn a strange city into home.",
 "p054.jpg": "The journey concludes as Spondon Nath of TE-IT relives the trembling JEE result morning — 'Qualified' glowing on screen, tears in his mother's arms — before Pune's tapris and FC Road nights become the newest home, and destiny keeps wandering.",
 "p055.jpg": "Diya Dawra of FY-E&TC invites us aboard in 'Enjoy the Journey of LIFE..' — life as a train ride where mistakes are human, small moments teach more than degrees, and gratitude belongs to everyone who ever shared our compartment.",
 "p056.jpg": "In 'Just A Mess', Yuvraj Nandapurkar of FY-CE wanders between temple incense and a windswept rooftop where he first loved — a searching poem weighing grief against blame, nostalgia against what never came to be, still seeking answers.",
 "p057.jpg": "Arfat Kadvekar of TE-CE drifts through clouds in 'Dreaming Us' — a playful poem where a girl's loving scoldings feel like hugs and her presence mends everything, until the alarm rings and the sweet dream slips over and out.",
 "p058.jpg": "In 'The Overlap', Prem Rahinj of BE-CE watches his seven-year-old niece cry at Inside Out and ask why Sadness is always sad — unfolding into a gentle meditation on how emotions arrive tangled, and how life lives in that middle.",
 "p059.jpg": "'Infrastructure: The Invisible Layer' begins with an iceberg — the cables, servers, and protocols beneath every app. From Netscape's big bang to India's DPI stack of Aadhaar, UPI, and DigiLocker, it celebrates the plumbing that makes the flashy bits possible.",
 "p060.jpg": "The story continues in Kenya, where Aarya Badhe of BE-IT recounts the M-PESA moment — mobile money reaching remote villages — before weighing infrastructure's power against dependency, sovereignty, and surveillance. Infrastructure isn't visible until it disappears.",
 "p061.jpg": "In 'Synthesized, Not Stolen', Vedika Bopche and Parth Patil sing the story of Vocaloid — bedroom producers, digital voices like LEON and LOLA, and ethical synthesis versus voice-cloning theft — insisting the human heart must keep beating inside the machine.",
 "p062.jpg": "Ritvik Mohit Kheur of SY-E&TC salutes India's soldiers in 'Jai Jawan' — a stirring tribute to those guarding land, water, and air, far from family, carrying a nation's burden on their shoulders. All we say is Jai Jawan!",
 "p063.jpg": "Nehal Shivane of BE-CE stirs together 'The Recipe for A Perfect Sunset' — chasing warm orange skies through forests, beaches, and mountains, weathering rain and tears, only to find the perfect sunset was waiting at home all along.",
 "p064.jpg": "In 'Voices of the Unspoken', Kumud Kojabe of SY-IT wonders whether poets, artists, dancers, and songwriters exist to give our wordless feelings shape — a lyrical tribute to every art form carrying its own quiet meaning and care.",
 "p065.jpg": "A patchwork of 'Very Short Stories' — nine students, from Aaliya Phirphire to Divya Jain, each completing the prompt 'The map didn't show that lane, yet my feet knew where to turn' with tales of shores, devotion, graduation goodbyes, and friendship.",
 "p066.jpg": "An inspiring conversation begins with IFS officer Sayali Mhetre, a PICT alumna serving in Israel — recalling how she stumbled into engineering, discovered a different mindset abroad, and learned to keep the UPSC exam from overpowering life itself.",
 "p067.jpg": "The interview continues as Sayali Mhetre recalls COVID teaching her life's fragility, leaving a young tech job to prepare full-time, rebuilding self-trust after setbacks, and her father's advice that people respect the office, so serve without ego.",
 "p068.jpg": "The conversation deepens: Sayali speaks of working for the people she sees daily, why engineers thrive in civil services, the interpersonal skills young IFS aspirants need, and how PICT's Pictoreal and Pictosocial taught her to think beyond machines.",
 "p069.jpg": "The interview concludes with Sayali choosing Marathi Literature out of love rather than strategy, reflections on diplomacy's quiet freedom, and her gratitude journal — closed warmly by the Pictoreal team on a late-night video call.",
 "p070.jpg": "From the Pictopods series comes 'The Heroes Behind Lila Poonawalla Foundation' — honouring Lila, Padma Shri awardee and pioneering woman engineer-CEO, and Firoz Poonawalla, whose foundation has empowered over 14,000 'Lila Daughters' through education and mentorship.",
 "p085.jpg": "A gallery bursting with talent — PICT Arts gathers student artwork from Kaivalya Deshpande's Lata Mangeshkar portrait to Shivaji Maharaj, Deadpool, Krishna, Madhubani elephants, and Dhoni in blue ballpoint — every frame a labour of love.",
 "p086.jpg": "PICT Photography celebrates campus shutterbugs — sunsets and storks, temple silhouettes and mountain rivers, a curious cat by the window, and Jaisalmer's carved balconies — twenty-odd frames of the world seen through students' patient, wandering lenses.",
 "p071.jpg": "आइए, पहला पन्ना खोलें — अयान पठान का लेख 'एहसास'। माँ का सर पर हाथ, बारिश की पहली फुहार, ग़ज़ल का कोई शेर — जीवन के ऐसे अनमोल एहसासों को यह लेख बड़े प्यार से सहेजता है और आगे बढ़ने की उम्मीद जगाता है।",
 "p072.jpg": "अब सुनिए 'स्नेह बंधन' — प्रद्योत जयेश म्हैसकर की प्यारी कहानी दो भाइयों की। बचपन की लड़ाई-झगड़े, माँ का बेलन, और फिर दूरियों में पनपता गहरा प्यार — भाई का रिश्ता सचमुच खुदा की अनमोल नियामत है।",
 "p073.jpg": "हर्षित व्होरा और ओंकार देसाई पूछते हैं 'आसान ज़िंदगी की कठिन सच्चाई' — नानाजी को हर गली याद है, पर हमें GPS चाहिए! तकनीक और AI ने जीवन आसान किया, पर कहीं हम अपना स्वावलंबन और इंसानियत तो नहीं खो रहे?",
 "p074.jpg": "अब बात नींद की — 'बंद आँखें, खुली ज़िंदगी'। हम थकान को सफलता की निशानी मानने लगे हैं, पर नींद तो शरीर और मन की मरम्मत का समय है। यह लेख अच्छी नींद के आसान, प्यारे नुस्खे भी बताता है।",
 "p075.jpg": "वही लेख आगे बढ़ता है — पलक राठी बताती हैं कि विज्ञान नींद के बारे में क्या कहता है। सौ साल पहले इंसान नौ घंटे सोता था, आज साढ़े छह! Insomnia महामारी बन रही है, इसलिए आज रात बस एक काम करें — सो जाइए।",
 "p076.jpg": "वेदांत देशमुख का सुंदर लेख 'हम सच नहीं, उसका आसान हिस्सा देखते हैं' — हर तस्वीर के पीछे कई सच छुपे होते हैं। कैमरा पल कैद करता है, पर सबसे हसीन यादें अक्सर बिना तस्वीर के ही दिल में बसती हैं।",
 "p077.jpg": "अब चलिए 'भारत की वास्तुकला' की सैर पर — श्रद्धा डोळस सुनाती हैं दीवारों के बीच छुपी कहानियाँ। आँगन की हँसी से काँच की ऊँची इमारतों तक, यह लेख पूछता है — क्या हम प्रकृति से अपना खोया रिश्ता फिर गढ़ सकते हैं?",
 "p078.jpg": "अंजनी गुळवे और प्रेम राहिंज कहते हैं — 'खूबसूरत ज़िंदगी' रील्स में नहीं, आपकी अपनी सुबह की चाय में है। फर्क ज़िंदगी का नहीं, नज़रिये का है। जो हो रहा है, बस उसे महसूस कीजिए — यही जीने की कला है।",
 "p079.jpg": "अब एक कोमल कविता — ओमकार देसाई पूछते हैं 'मन नहीं करता तुम्हारा?' सब छोड़कर किसी शांत नदी किनारे बैठने का, चाँद ताकने का, फ़ॉर्मूलों की जगह चिट्ठियाँ लिखने का... सच बताओ, तुम्हारा भी मन करता है ना?",
 "p080.jpg": "अक्षरा गुप्ता की कविता 'उस गर्दिश में मौजूद सबसे चमकीले तारे से' — एक ऐसे शहर की तलाश जहाँ बिना किसी दौड़ में उतरे ही जीत मिले, जहाँ मन का कोलाहल थमे, और जहाँ वह खोज पाए... खुद को।",
 "p081.jpg": "सारंग राव की कविता 'तब लिखो' — लिखो तब जब कागज़ आँसुओं से भर जाए, जब चाँद किसी और के किस्से सुनाए, जब दिल में काफ़ी कुछ जमा हो जाए। खुद को मुमकिन लिखने का यही तो मौक़ा है!",
 "p082.jpg": "अब लघुकथा का पन्ना — 'वो सपने, जो मैंने कभी देखे थे, अब पूरे हो रहे थे।' मयूर चावरे, अमेय सुर्वे, पार्थ पाटील और क्षितिज ढाके की छोटी-छोटी रचनाएँ, उम्मीद और मेहनत के रंग लाने की मीठी कहानियाँ।",
 "p083.jpg": "'Creativity से Career तक' — ग्राफिक डिज़ाइनिंग के बदलते सफर पर 'औरंगाबादी मुसाफिर' यानी Mudassir Nadeem से खास बातचीत। डिज़ाइन का असली काम है समस्या का रचनात्मक हल — शुरुआत कैसे करें, कौन-सी skills सीखें, सब यहाँ है।",
 "p084.jpg": "वही बातचीत आगे बढ़ती है — AI डिज़ाइनर की जगह नहीं लेगा, वह तो साथी है! Canva से creativity, logo और रंगों का मनोविज्ञान, और freshers के लिए प्यारी सलाह — portfolio बनाओ, सीखते रहो, तुलना मत करो।",
 "p087.jpg": "चला, सुरुवात करूया एका खुसखुशीत लेखाने! 'मी आणि माझा शत्रुपक्ष' मध्ये रेवती रानडे साडी नेसण्याच्या संघर्षाची गंमत सांगते — पिना, पदर, निऱ्या आणि तासन्‌तास आरशासमोरची झटापट. हसू आणि सहानुभूती दोन्ही जागवणारा हा मिश्किल अनुभव.",
 "p088.jpg": "आता जरा अंतर्मुख करणारा लेख — 'शब्द मागे सरकले, आपणही?'. कोऱ्या वहीसमोर बसलेल्या लेखिकेला जाणवतं की मराठी शब्द हळूहळू दूर जाताहेत, हिंग्लिशची सवय झालीये. आपल्या भाषेपासून आपण नकळत दुरावतोय का, हा प्रश्न मनाला भिडतो.",
 "p089.jpg": "हाच विचार पुढे नेत श्रुती मुंढे सांगते — भाषा बदलणं आणि हरवणं यात फरक आहे. मोठे निर्णय नकोत, फक्त रोज थोडं जास्त मराठी बोलणं, वाचणं, चुकांना न घाबरणं. भाषा परिपूर्ण नव्हे, जिवंत ठेवणं महत्त्वाचं, हा गोड समारोप.",
 "p090.jpg": "माही शाहचा 'रिटायरमेंट नंतरची आई आणि तिची सेकंड इनिंग!' हा प्रसन्न लेख. योगवर्ग, भिशी, सत्संग, मैत्रिणी अशा व्यस्त दिनचर्येत रमलेली साठीनंतरची आई — तिचं स्वातंत्र्य आनंदाने स्वीकारूया आणि म्हणूया, जिओ जी भर के!",
 "p091.jpg": "आता एक स्वप्नाळू कविता — सारंग रावची 'चांदण्यांची मैफिल'. चांदण्यांनी उजळलेल्या रात्री कवीचं मन हरवून जातं; नातं, स्वप्नं आणि खिडकीतली चांदणी यांच्या साथीने रंगलेली ही रात्रीची मैफिल मनाला शांत गारवा देते.",
 "p092.jpg": "निसर्ग कदमची 'पुन्हा अनोळखी' ही हळवी कविता. अनोळखीपणातून झालेली ओळख, गप्पांची सवय, आणि मग हळूहळू वाढत गेलेलं अंतर — राग नाही, चूक नाही, फक्त वेळ वेगळी वळली. ओळख पुन्हा परकी होण्याची चटका लावणारी गोष्ट.",
 "p093.jpg": "आता जिभेला पाणी सुटेल! किरण काळे यांचा 'मिसळ पाव: झणझणीत चवीचा अस्सल मराठमोळा जल्लोष'. कोल्हापुरी तिखट, पुणेरी संतुलित, नाशिकची गोडसर — मिसळीच्या रूपांतून महाराष्ट्राच्या खाद्यसंस्कृतीची आणि जिव्हाळ्याची ही रुचकर सफर.",
 "p094.jpg": "प्रा. योगेश हांडगे यांचा भावुक लेख — 'समारोप नव्हे, नव्या कोडची सुरुवात'. कॉम्प्युटर इंजिनिअरिंगच्या विद्यार्थ्यांचा निरोप समारंभ, पहिल्या 'सेगमेंटेशन फॉल्ट'पासून प्लेसमेंटपर्यंतच्या आठवणी, आणि चार वर्षांत घडलेली मैत्री अन् आत्मविश्वासाची शिदोरी.",
 "p095.jpg": "श्रुती मुंढेची 'असावा असा कोणीतरी…' ही आर्त कविता. न बोलावता गरजेला हजर असणारा, चुकांसाठी रागावणारा, रडताना हसवणारा — असा आपल्याहून जास्त आपल्यावर प्रेम करणारा जिवलग प्रत्येकाला हवा असतो, ही भावना थेट काळजाला भिडते.",
 "p096.jpg": "आता इतिहासाची सफर — 'पडसाद: वास्तू आणि' या लेखात तुळजापूरची तुळजाभवानी आणि कार्ला लेणी यांच्या ऐतिहासिक प्रवासातून प्रश्न विचारला जातो: वास्तूचं मूळ आणि उद्देश हरवले तर उरतं काय? विचार करायला लावणारी मांडणी.",
 "p097.jpg": "याच चिंतनाचा पुढचा भाग — 'वास्तव: एक मीमांसा'. सिद्धी आंबेकर हंपीच्या वैभवशाली अवशेषांतून विचारते: आपण फक्त दगड जपतोय की त्यामागची निर्मितीची जिद्द? वारसा प्रदर्शनाची वस्तू नसून जगण्याचा वसा आहे, हा संदेश.",
 "p098.jpg": "चैतन्य कुलकर्णीची 'पुरुषार्थ' ही रूपकात्मक कविता. कुजलेल्या वडाभोवती जमलेले सारे, चिखलात फेकलेलं रोपटं आणि धाडस दाखवणारा पिंपळ — पोकळ मोठेपणा आणि खरा पुरुषार्थ यांतला फरक निसर्गाच्या प्रतिमांतून मार्मिकपणे उलगडतो.",
 "p099.jpg": "प्रतीक्षा बोरसेचा प्रभावी लेख 'हे कृष्णे…'. द्रौपदीच्या रूपाने प्रत्येक युगातल्या स्त्रीच्या अपमानाचा प्रश्न मांडत, कलियुगातल्या स्त्रीला ती सांगते — तू स्वतःच तुझा कृष्ण हो, प्रवाह हो, किनारा नाही. अंगावर काटा आणणारं स्त्रीशक्तीचं आवाहन.",
 "p100.jpg": "'अहिराणी: घर, माणसं आणि आठवणी' — खान्देशी बोलीचा गंध सांगणारा लेख. जात्यावरच्या ओव्या, शेतातल्या हाका, सणांची बोली… आणि 'Coming Aaji' म्हणणारा नातू. भाषा ऐकली जाते पण बोलली जात नाही, ही आजीची हलकीशी खंत.",
 "p101.jpg": "आजीच्या गोष्टीने हा लेख पुढे सरकतो — दुष्काळात विहीर खोदणाऱ्या गावाची अहिराणीतली कहाणी ऐकून नातवाला उमगतं: जमीन आपली, भाषा आपली, जपली तरच टिकेल. कस्तुरी वैद्य सांगते, भाषा टिकते ती बोलण्यात, घरात आणि मनात.",
 "p102.jpg": "इंद्रजीत दोडमिसेची 'विद्रोह' ही धगधगती कविता. श्रीमंतांची रोज दिवाळी आणि गरिबांच्या वाट्याला यातना — या विषमतेने पेटलेलं मन अन्यायाविरुद्ध शिरांतून उसळणारा विद्रोह मांडतं. वंचितांच्या वेदनेला दिलेली ही रोखठोक वाचा.",
 "p103.jpg": "प्रा. योगेश हांडगे यांची उपरोधिक कविता 'पुढारी राजा'. बँडबाजात निवडून आलेला पुढारी, विकासाची भाषणं, लोभाचा पाऊस आणि भ्रष्टाचाराचं बीज — पाच वर्षांनी पुन्हा तोच सभारंभ! राजकारणावरचं हे मार्मिक भाष्य हसवता हसवता अंतर्मुख करतं.",
 "p104.jpg": "कल्याणी देशपांडेचा 'वेळेपलीकडचं सौंदर्य' हा हृदयस्पर्शी लेख. आजीने विणलेला स्वेटर, हाताने लिहिलेलं पत्र, वारली-धोकरासारखी हस्तकला — यंत्राच्या अचूकतेत न सापडणारी ऊब हस्तनिर्मित गोष्टींत असते; त्या वापरण्यासाठी नव्हे, आयुष्यभर जपण्यासाठी असतात.",
 "p105.jpg": "आता एक अभिमानाची भेट — खो-खो वर्ल्ड कप विजेती प्रियांका इंगळे हिची मुलाखत! बीडच्या गावातून राष्ट्रीय स्तरापर्यंतचा प्रवास, घरच्यांचा सुरुवातीचा विरोध आणि खेळावरच्या प्रेमाने घडवलेली जिद्द — प्रेरणेने भारलेली ही बातचीत.",
 "p106.jpg": "प्रियांकाची मुलाखत रंगत जाते — कर्णधारपदाचा अनुभव, दडपण हाताळण्याची कला, सोळा वर्षांत एकही दुखापत नसण्याचं रहस्य आणि मराठी शाळेपासून वर्ल्ड कपपर्यंतचा प्रवास. पिक्टोरियल टीमने घेतलेल्या या गप्पा तरुण खेळाडूंना बळ देणाऱ्या.",
 "p107.jpg": "पिक्टोपॉड्स सदरात 'त्या आवाजामागची कथा' — किराणा घराण्याचे गायक आनंद भाटे यांची ओळख. 'आनंद गंधर्व' पदवी, भीमसेन जोशींचं शिष्यत्व, इंजिनिअरिंग आणि संगीताचा दुहेरी प्रवास — सूर आणि साधनेची ही चिरंतन कहाणी.",
 "p108.jpg": "शेवटी लघुकथांचा गोड गुच्छ — 'जे सापडलं, ते हरवलं होतं असं मला माहीतच नव्हतं…'. श्रावणी, पार्थ, कस्तुरी, सिद्धी अशा अनेकांच्या छोट्या कथा: जुनी नोट, धूळभरली पिशवी, वर्गफोटो… हरवलेल्या आठवणी अचानक गवसण्याचे हळवे क्षण.",
 "p002.jpg": "Here are the hands behind it all - the coordinators, secretaries and the tireless teams of Pictosocial, Marketing, Production, Pictotech, Interview and Social Media who poured themselves into this volume.",
 "p003.jpg": "And still the roll call of makers continues - the heads and the loyal crews of Event Management, Photography, Design and Editorial, each name a thread woven into Pictoreal.",
 "p004.jpg": "Let us pause and hold them gently in our hearts - Purti Patil and Ayush Harinkhede, dear friends whose laughter still lingers in these corridors. Though they left too soon, their light walks beside us always.",
 "p005.jpg": "A moment of tribute to the greats we lost this year - Ajit Pawar, the singer Asha Bhosle, the icons Dharmendra and Manoj Kumar, visionary Ravi Pandit of KPIT, and filmmaker Bharathiraja. Their gifts outlive them.",
 "p006.jpg": "Behold the whole PICT family gathered under the old trees - teachers, staff and friends standing together, the warm heartbeat of this institution.",
 "p007.jpg": "And here is Team Pictoreal itself, the whole spirited crew whose late nights and shared dreams gave this magazine its life.",
 "p008.jpg": "The Class of 2026, gathered one last time upon the green - the end of a chapter, yet, as they say, the beginning of everything.",
 "p009.jpg": "A word from Shri R. S. Kothavale, Managing Trustee of SCTR, who reminds us that a magazine becomes memorable not because it appears each year, but because it captures the very spirit of its time.",
 "p010.jpg": "From the desk of Secretary Shri S. M. Sirsikar, who cherishes Pictoreal as a valued tradition - a platform where students think freely, engage deeply and preserve their voices for years to come.",
 "p011.jpg": "Director Dr. P. T. Kulkarni welcomes us warmly, unveiling this year's theme, Anvesha - a journey through culture, memory and identity, painting the real picture of PICT.",
 "p012.jpg": "Principal Dr. S. T. Gandhe shares his joy in seeing young minds create and express, celebrating a campus made vibrant by curiosity, courage and heartfelt effort.",
 "p013.jpg": "Magazine Coordinator Mrs. A. A. Joshi speaks of Anvesha - that beautiful Sanskrit word for search and discovery - reminding us that learning is a lifelong journey of seeking and wonder.",
 "p014.jpg": "Coordinator Mr. Y. A. Handge greets us with the full theme - Anvesha, discovering the new within the embrace of the old - a mindset that honours legacy while chasing fresh horizons.",
 "p015.jpg": "Meet the core - Magazine Secretaries Amulya Agrawal and Prem Rahinj, and Joint Secretaries Sampada Tagalpallewar and Kshitij Dhake, who carried Volume 28 upon their shoulders with love.",
 "p016.jpg": "Meet the core - General Secretaries Unnati Rathi and Aarya Badhe, and Treasurer Kartik Tichkule, who steered every plan, every rupee and every late-night worry with heart.",
 "p017.jpg": "Meet the core - the Design Heads Saanvi Bhavsar, Anjani Gulve and Sanvi Waghmode who shaped how it looks, and Editorial Heads Spondon Nath, Sanavi Kulkarni and Ayan Pathan who shaped what it says.",
 "p018.jpg": "Meet the core - Pictosocial Heads Dhanashri Mahadik, Harshit Vora and Sukanya Gupta who gave back to the world, alongside Event Managers Vedika Bopche, Jeet Amin and Omkar Desai.",
 "p019.jpg": "Meet the core - Public Relations Officers Shraddha Dolas, Trishit Guin and Maria Shaikh, and Social Media Heads Pushkar Mulajkar, Samierra Arora and Aditya Tidake, the voice and face of Pictoreal.",
 "p020.jpg": "Meet the core - Photography Heads Shantanu Sable and Mahesh Loya who froze time in every frame, and Pictotech Heads Madhura Deshmukh, Manas Gawali and Riddhi Lahare who built the platforms beneath it all.",
 "p021.jpg": "Meet the core - Marketing Heads Pratik Chavan, Gauravi Mutha and Manas Yeola who forged real partnerships, and the first-ever Production Heads Pranav Wagh and Vihan Wani.",
 "p022.jpg": "The mentors of the Department of Computer Engineering, gathered with pride - the guiding minds who shape tomorrow's makers.",
 "p023.jpg": "The esteemed faculty of the Department of Electronics and Telecommunication Engineering, teachers who turn signals into stories and students into engineers.",
 "p024.jpg": "The dedicated faculty of the Department of Information Technology, keepers of the code and the curiosity behind it.",
 "p025.jpg": "The faculty of the Department of Artificial Intelligence and Data Science Engineering, charting the newest frontiers alongside their students.",
 "p026.jpg": "The mentors of the Department of Electronics and Computer Engineering, standing together with warmth and wisdom.",
 "p027.jpg": "The faculty of the Department of Basic Science and Engineering, who welcome every First Year and lay the very foundation of the journey.",
 "p028.jpg": "The scholars and guides of M.E. and PhD Computer Engineering, nurturing research and deeper inquiry.",
 "p029.jpg": "The faculty of M.E. and PhD Electronics and Telecommunication Engineering, mentors of advanced minds and bold ideas.",
 "p030.jpg": "The devoted team of the Training and Placement Cell, who open doors to futures and walk students to the threshold of their dreams.",
 "p031.jpg": "The unsung hearts of Library, Accounts, Sports and Administration - the steady hands that keep this whole institution running.",
 "p032.jpg": "And the ever-caring Housekeeping and Security family, the quiet guardians whose service keeps our campus safe and shining.",
 "p033.jpg": "The graduating faces of BE-01, Computer Engineering - four years of friendship and effort, now ready to step into the world.",
 "p034.jpg": "BE-02, Computer Engineering - a batch of dreamers and doers, gathered proudly on the eve of their farewell.",
 "p035.jpg": "BE-03, Computer Engineering - one more circle of friends who turned classrooms into memories worth keeping.",
 "p036.jpg": "BE-04, Computer Engineering - the last of the Computer Engineering batches, beaming with the promise of what lies ahead.",
 "p037.jpg": "BE-05, Electronics and Telecommunication Engineering - a spirited batch ready to send their signals out into the wide world.",
 "p038.jpg": "BE-06, Electronics and Telecommunication Engineering - bright faces and warm bonds, captured just before they scatter to their futures.",
 "p039.jpg": "BE-07, Electronics and Telecommunication Engineering - a family of engineers, smiling through the bittersweet joy of goodbye.",
 "p040.jpg": "BE-08, Electronics and Telecommunication Engineering - one more cherished batch closing a beautiful chapter together.",
 "p041.jpg": "BE-09, Information Technology - a lively batch who coded, laughed and grew as one, now ready to fly.",
 "p042.jpg": "BE-10, Information Technology - friends bound by late submissions and lasting memories, stepping forward with pride.",
 "p043.jpg": "BE-11, Information Technology - the final graduating batch, carrying four golden years of PICT within their hearts.",
 "p044.jpg": "And a heartfelt salute to the Outstanding Performers of 2025 - the shining scholars across every year and branch, whose brilliance lights the way for all who follow.",
 "p109.jpg": "Meet the winners of Aamche Bappa, our Ganesh celebration contest, where Anusha, Yash, Om and Jayesh brought Bappa home with the most loving decorations, reels and photographs.",
 "p110.jpg": "Now step into Jhalak Diwalichi, our festival of lights, where these bright souls turned rangoli, diyas and cosy corners into pure Diwali magic.",
 "p111.jpg": "Here stand the winning team of Manthan, our public speaking contest, with Shreyank crowned Best Speaker. Words, well spoken, can light up a whole room.",
 "p112.jpg": "Feast your eyes on the Pics-O-Reel winners, where a single frozen frame and a stroke of the pencil captured stories that need no words.",
 "p113.jpg": "And the Pics-O-Reel journey continues, through painting, graffiti scripts and the Everyday India theme, celebrating the beauty we so often walk right past.",
 "p114.jpg": "Come closer, these little stamps hold our fondest memories, snapshots of laughter, friendship and countless joyful days spent together on campus.",
 "p115.jpg": "This is the Making of Pictoreal, dear reader, the late nights, chai breaks and warm chaos behind these pages, from your Sutradhar with love.",
 "p116.jpg": "Turn with me through our Event Reports, from Pictoplants and Manthan to Parichay and the proud Code The Cause hackathon, each a story of heart and effort.",
 "p117.jpg": "More of our stories unfold here, the orphanage visit, the blood donation drive, the colourful Pictofest, and the emotional farewell of the BE Photoshoot.",
 "p118.jpg": "A warm salute to our Event Coordinators, the quiet hands behind Code The Cause, Parichay, the Orphanage Visit and Pictoplants, who turned plans into memories.",
 "p119.jpg": "And here are more of our tireless coordinators, guiding the Blood Donation Drive, Pictofest and the BE Photoshoot with dedication and heart.",
 "p120.jpg": "A gentle bow to the coordinators of our Magazine Release, Tanishka, Kasturi, Vidhi and Kumud, who helped bring this very book into your hands.",
 "p121.jpg": "Relive Pictoplants, where we planted saplings on the hills, and the Orphanage Visit, where colours and games filled little hearts with joy.",
 "p122.jpg": "Here bloom the memories of Parichay and Manthan, and our proud Code The Cause hackathon, where fresh minds gathered to build for a better world.",
 "p123.jpg": "Step into the vibrant world of Pictofest, our fiesta of art, pottery, resin ponds and that unforgettable painted bus, where thoughts, colours and words prevailed.",
 "p124.jpg": "Two heartfelt days live here, the life-saving Blood Donation Drive, and the BE Photoshoot, the final chapter for our graduating batch to soak in their last campus moments.",
 "p125.jpg": "Meet PICT's Electoral Literacy Club, kindling responsible citizenship through voter drives and pledges, strengthening our democracy one young voter at a time.",
 "p126.jpg": "Behold PICT Robotics, our national champions, whose Galactic Gearheads outflew five hundred teams to win the ISRO Drone Challenge with sheer engineering brilliance.",
 "p127.jpg": "Here roars the PICT Automobile Club, five years of teamwork and torque, building go-karts from the ground up and racing every lesson into triumph.",
 "p128.jpg": "Feel the speed and camaraderie of the Automobile Club's year, from workshops to racetracks, where grease-stained hands and bright smiles built something to be proud of.",
 "p129.jpg": "Meet PICT ACM, a four-time Best Student Chapter, nurturing technologists through Pulzion, hackathons and hands-on interest groups with tireless passion.",
 "p130.jpg": "Relive Pulzion, ACM's flagship fest themed on the AI Gridlock, buzzing with thirteen competitions and the eager energy of students from far and wide.",
 "p131.jpg": "Here thrives PICT CSI, one of Pune's most active branches, whose fest Xenia drew over five hundred curious minds into a world of innovation.",
 "p132.jpg": "Step through the three lively days of Xenia, CSI's tech fest, alive with hackathons, expert talks and students collaborating across colleges.",
 "p133.jpg": "Meet PICT IEEE, a hub of innovation whose flagship Credenz 2026 brought technologists together to celebrate learning, competition and open-source spirit.",
 "p134.jpg": "Relive Credenz, IEEE's grand fest, glowing with fairy lights, painted backdrops and the joyful faces of a community that codes and creates as one.",
 "p135.jpg": "Enter GameDevUtopia, PICT's game development club, whose flagship Glitched showcased over fifty games, digital art and even a short film made entirely in-house.",
 "p136.jpg": "Follow GameDevUtopia beyond campus, to industry visits, the Women in Games booth and their proud wins at the Genesis GameJam.",
 "p137.jpg": "Meet PICT's Entrepreneurship Cell, where bold ideas take flight, from a Prison Escape induction to Magnate, their spirited celebration of innovation and business.",
 "p138.jpg": "Relive Magnate, the EDC's flagship fest, buzzing with ideathons, Wall Street thrills and young founders daring to dream and build.",
 "p139.jpg": "Here shines the PICT Art Circle, our vibrant family of actors, singers, dancers and designers, whose talent earned accolades on stage after stage. United, we rock.",
 "p140.jpg": "Feel the applause of the Art Circle's year, one-act plays, folk songs, Mood Indigo and Firodiya, where our artists poured their hearts into every performance.",
 "p141.jpg": "Meet PICT NSS, guided by Not Me But You, whose volunteers planted trees, cleaned rivers, tied rakhis for soldiers and served with quiet, tireless compassion.",
 "p142.jpg": "Witness NSS in action, from village camps and river cleaning to blood donation and heartfelt community visits, service above self in every frame.",
 "p143.jpg": "Here stands PICT DEBSOC, where voices grow bold, through debates, group discussions and their flagship Paricharcha that welcomed over a hundred speakers.",
 "p144.jpg": "Relive Paricharcha, DEBSOC's grand intercollegiate stage, where spontaneity, argument and confidence met in spirited, thoughtful debate.",
 "p145.jpg": "Meet PICT TEDx and their event Nirantar, meaning continuity, where over two hundred hearts gathered for ideas, music and the endless flow of curiosity.",
 "p146.jpg": "Relive Nirantar's magic, glowing stages, live music, clay workshops and warm conversations that lingered long after the final talk had ended.",
 "p147.jpg": "Here is PICT MUN, our largest non-technical gathering, where young diplomats debate world agendas and grow into the leaders and thinkers of tomorrow.",
 "p148.jpg": "Behold Impetus and Concepts, PICT's flagship technical fest in its thirty-ninth year, drawing over eight thousand minds and projects from across the globe.",
 "p149.jpg": "Relive the grandeur of InC, from packed inaugurations to prize-winning innovations, where budding engineers turned bold ideas into reality.",
 "p150.jpg": "Feel the pulse of Addiction, our cultural fest, alive with dance, music, drama and fashion, a dazzling celebration of energy and expression.",
 "p151.jpg": "Relive Addiction's electric days, back-to-back performances, dapper crowds and a campus glowing with talent, creativity and pure celebration.",
 "p152.jpg": "A proud salute to PICT Sports, where our champions shone in volleyball, basketball and beyond, bringing home medals and glory across university and national arenas.",
 "p153.jpg": "Here stand our sporting heroes with their trophies held high, teammates who sweated, cheered and triumphed together on court and field.",
 "p154.jpg": "And here glow our basketball and Pentacle champions, refusing to lose, their cabinet of cups a testament to grit, teamwork and the joy of the game."
};
