// GENERATED by scripts/build-real-pages.mjs from public/pages/real/manifest.txt
// The real Pictoreal Vol. 28 draft pages, in magazine order.
export const realTiers = [
  {
    "id": "opening",
    "name": "Opening Pages",
    "section": "Opening Pages",
    "lang": "en",
    "caption": "Pictoreal · Vol. 28",
    "intro": "Every volume opens with an invocation. Walk slowly here.",
    "pages": [
      {
        "file": "p001.jpg",
        "title": "Saraswati Vandana"
      },
      {
        "file": "p002.jpg",
        "title": "The Makers — I"
      },
      {
        "file": "p003.jpg",
        "title": "The Makers — II"
      },
      {
        "file": "p004.jpg",
        "title": "In Remembrance"
      },
      {
        "file": "p005.jpg",
        "title": "Tributes"
      },
      {
        "file": "p006.jpg",
        "title": "The PICT Family"
      },
      {
        "file": "p007.jpg",
        "title": "Team Pictoreal"
      },
      {
        "file": "p008.jpg",
        "title": "Batch of 2026"
      }
    ]
  },
  {
    "id": "messages",
    "name": "Blessings & Messages",
    "section": "Blessings & Messages",
    "lang": "en",
    "caption": "From our mentors",
    "intro": "First, the hands that steady the lamp — words from those who guide PICT.",
    "pages": [
      {
        "file": "p009.jpg",
        "title": "trustee"
      },
      {
        "file": "p010.jpg",
        "title": "secretary"
      },
      {
        "file": "p011.jpg",
        "title": "director"
      },
      {
        "file": "p012.jpg",
        "title": "principal"
      },
      {
        "file": "p013.jpg",
        "title": "Asmitamaam"
      },
      {
        "file": "p014.jpg",
        "title": "handgesir"
      }
    ]
  },
  {
    "id": "faculty",
    "name": "Faculty & Departments",
    "section": "Faculty & Departments",
    "lang": "en",
    "caption": "The departments",
    "intro": "Every hall of learning, and the teachers who keep its flame.",
    "pages": [
      {
        "file": "p015.jpg",
        "title": "MS-JS"
      },
      {
        "file": "p016.jpg",
        "title": "GS-T"
      },
      {
        "file": "p017.jpg",
        "title": "DH-EH"
      },
      {
        "file": "p018.jpg",
        "title": "PSH-EM"
      },
      {
        "file": "p019.jpg",
        "title": "PRO-SMH"
      },
      {
        "file": "p020.jpg",
        "title": "PH-PTH"
      },
      {
        "file": "p021.jpg",
        "title": "MH-PH"
      },
      {
        "file": "p022.jpg",
        "title": "CE DEPT"
      },
      {
        "file": "p023.jpg",
        "title": "E&TC DEPT"
      },
      {
        "file": "p024.jpg",
        "title": "IT DEPT"
      },
      {
        "file": "p025.jpg",
        "title": "AIDS DEPT"
      },
      {
        "file": "p026.jpg",
        "title": "ECE DEPT"
      },
      {
        "file": "p027.jpg",
        "title": "F.Y.DEPT"
      },
      {
        "file": "p028.jpg",
        "title": "ME PhD CE"
      },
      {
        "file": "p029.jpg",
        "title": "ME PhD ENTCE"
      },
      {
        "file": "p030.jpg",
        "title": "TNP"
      },
      {
        "file": "p031.jpg",
        "title": "Admin"
      },
      {
        "file": "p032.jpg",
        "title": "Housekeeping"
      }
    ]
  },
  {
    "id": "batch",
    "name": "Batch of 2026",
    "section": "Batch of 2026",
    "lang": "en",
    "caption": "The graduating batch",
    "intro": "The seekers themselves — the Batch of Twenty Twenty-Six.",
    "pages": [
      {
        "file": "p033.jpg",
        "title": "BE1"
      },
      {
        "file": "p034.jpg",
        "title": "BE2"
      },
      {
        "file": "p035.jpg",
        "title": "BE3"
      },
      {
        "file": "p036.jpg",
        "title": "BE4"
      },
      {
        "file": "p037.jpg",
        "title": "BE5"
      },
      {
        "file": "p038.jpg",
        "title": "BE6"
      },
      {
        "file": "p039.jpg",
        "title": "BE7"
      },
      {
        "file": "p040.jpg",
        "title": "BE8"
      },
      {
        "file": "p041.jpg",
        "title": "BE9"
      },
      {
        "file": "p042.jpg",
        "title": "BE10"
      },
      {
        "file": "p043.jpg",
        "title": "BE11"
      },
      {
        "file": "p044.jpg",
        "title": "ToppersList"
      }
    ]
  },
  {
    "id": "english",
    "name": "English Section",
    "section": "English Section",
    "lang": "en",
    "caption": "English",
    "intro": "Stories and essays in English — voices young and searching.",
    "pages": [
      {
        "file": "p045.jpg",
        "title": "from nukes to navigation"
      },
      {
        "file": "p046.jpg",
        "title": "Unapologetically Me"
      },
      {
        "file": "p047.jpg",
        "title": "1 Text. 2 hours. 67 reels"
      },
      {
        "file": "p048.jpg",
        "title": "A Letter to My Younger Self"
      },
      {
        "file": "p049.jpg",
        "title": "ALoveLikeFireAndWind"
      },
      {
        "file": "p050.jpg",
        "title": "from cave walls to digital pixels"
      },
      {
        "file": "p051.jpg",
        "title": "from cave walls to digital pixels"
      },
      {
        "file": "p052.jpg",
        "title": "journey across states"
      },
      {
        "file": "p053.jpg",
        "title": "journey across states"
      },
      {
        "file": "p054.jpg",
        "title": "journey across states"
      },
      {
        "file": "p055.jpg",
        "title": "Journey Of Life"
      },
      {
        "file": "p056.jpg",
        "title": "Just A Mess"
      },
      {
        "file": "p057.jpg",
        "title": "DreamingUs"
      },
      {
        "file": "p058.jpg",
        "title": "The Overlap"
      },
      {
        "file": "p059.jpg",
        "title": "inffrastructure the invisible layer"
      },
      {
        "file": "p060.jpg",
        "title": "infrastructure the invisible layer"
      },
      {
        "file": "p061.jpg",
        "title": "Synthesized, Not Stolen"
      },
      {
        "file": "p062.jpg",
        "title": "Jai jawan"
      },
      {
        "file": "p063.jpg",
        "title": "the recipe for a perfect sunset"
      },
      {
        "file": "p064.jpg",
        "title": "voices of the unspoken"
      },
      {
        "file": "p065.jpg",
        "title": "English Vss"
      },
      {
        "file": "p066.jpg",
        "title": "English Interview"
      },
      {
        "file": "p067.jpg",
        "title": "English Interview"
      },
      {
        "file": "p068.jpg",
        "title": "English Interview"
      },
      {
        "file": "p069.jpg",
        "title": "English Interview"
      },
      {
        "file": "p070.jpg",
        "title": "english podcast"
      }
    ]
  },
  {
    "id": "hindi",
    "name": "हिन्दी विभाग",
    "section": "हिन्दी विभाग",
    "lang": "hi",
    "caption": "हिन्दी",
    "intro": "अब हिन्दी की गलियाँ — एहसास, कविताएँ और मुलाक़ातें।",
    "pages": [
      {
        "file": "p071.jpg",
        "title": "ehsaas"
      },
      {
        "file": "p072.jpg",
        "title": "स्नेहबंध"
      },
      {
        "file": "p073.jpg",
        "title": "आसान ज़िंदगी की कठिन सच्चाई"
      },
      {
        "file": "p074.jpg",
        "title": "बंद आँखें, खुली ज़िंदगी"
      },
      {
        "file": "p075.jpg",
        "title": "बंद आँखें, खुली ज़िंदगी"
      },
      {
        "file": "p076.jpg",
        "title": "हम सच नहीं, उसका आसान हिस्सा देखते हैं"
      },
      {
        "file": "p077.jpg",
        "title": "BharatKiVastukala"
      },
      {
        "file": "p078.jpg",
        "title": "खूबसूरत ज़िंदगी"
      },
      {
        "file": "p079.jpg",
        "title": "मन नहीं करता तुम्हारा"
      },
      {
        "file": "p080.jpg",
        "title": "उस गर्दिश में मौजूद सबसे चमकीले तारे से"
      },
      {
        "file": "p081.jpg",
        "title": "तब लिखो"
      },
      {
        "file": "p082.jpg",
        "title": "hindivss"
      },
      {
        "file": "p083.jpg",
        "title": "hindi interview"
      },
      {
        "file": "p084.jpg",
        "title": "hindi interview"
      }
    ]
  },
  {
    "id": "arts",
    "name": "Arts & Photography",
    "section": "Arts & Photography",
    "lang": "en",
    "caption": "PICT arts",
    "intro": "The eye behind the lens, the hand behind the brush.",
    "pages": [
      {
        "file": "p085.jpg",
        "title": "pict arts"
      },
      {
        "file": "p086.jpg",
        "title": "pict photography"
      }
    ]
  },
  {
    "id": "marathi",
    "name": "मराठी विभाग",
    "section": "मराठी विभाग",
    "lang": "mr",
    "caption": "मराठी",
    "intro": "आता मराठीचं दालन — कथा, कविता आणि गप्पा.",
    "pages": [
      {
        "file": "p087.jpg",
        "title": "मी आणि माझा शत्रुपक्ष"
      },
      {
        "file": "p088.jpg",
        "title": "shabd mage sarakale aapanahi"
      },
      {
        "file": "p089.jpg",
        "title": "shabd mage sarakale aapanahi"
      },
      {
        "file": "p090.jpg",
        "title": "रिटायरमेंट नंतरची आई आणि तिची सेकंड इनिंग"
      },
      {
        "file": "p091.jpg",
        "title": "चांदण्यांची मैफिल"
      },
      {
        "file": "p092.jpg",
        "title": "punha anolkhi"
      },
      {
        "file": "p093.jpg",
        "title": "MisalPav"
      },
      {
        "file": "p094.jpg",
        "title": "समारोप नव्हे, नव्या कोडची सुरुवात"
      },
      {
        "file": "p095.jpg",
        "title": "असावा असा कोणीतरी"
      },
      {
        "file": "p096.jpg",
        "title": "पडसाद वास्तू आणि वास्तव - एक मीमांसा"
      },
      {
        "file": "p097.jpg",
        "title": "पडसाद वास्तू आणि वास्तव - एक मीमांसा"
      },
      {
        "file": "p098.jpg",
        "title": "purusharth"
      },
      {
        "file": "p099.jpg",
        "title": "हे कृष्णे..."
      },
      {
        "file": "p100.jpg",
        "title": "L अहिराणी - घर, माणसं आणि आठवणी"
      },
      {
        "file": "p101.jpg",
        "title": "R अहिराणी - घर, माणसं आणि आठवणी"
      },
      {
        "file": "p102.jpg",
        "title": "विद्रोह"
      },
      {
        "file": "p103.jpg",
        "title": "पुढारी राजा"
      },
      {
        "file": "p104.jpg",
        "title": "VelepalikadchaSaundarya"
      },
      {
        "file": "p105.jpg",
        "title": "marathi interview"
      },
      {
        "file": "p106.jpg",
        "title": "marathi interview"
      },
      {
        "file": "p107.jpg",
        "title": "podcast marathi"
      },
      {
        "file": "p108.jpg",
        "title": "MarathiVSS"
      }
    ]
  },
  {
    "id": "events",
    "name": "Events & Celebrations",
    "section": "Events & Celebrations",
    "lang": "en",
    "caption": "The year's events",
    "intro": "The year as it was lived — festivals, contests and stage lights.",
    "pages": [
      {
        "file": "p109.jpg",
        "title": "Aamche Bappa Winners"
      },
      {
        "file": "p110.jpg",
        "title": "Jhalak diwalichi"
      },
      {
        "file": "p111.jpg",
        "title": "Manthan winners"
      },
      {
        "file": "p112.jpg",
        "title": "picsoreel"
      },
      {
        "file": "p113.jpg",
        "title": "picsoreel"
      },
      {
        "file": "p114.jpg",
        "title": "Making"
      },
      {
        "file": "p115.jpg",
        "title": "Making"
      },
      {
        "file": "p116.jpg",
        "title": "eventreports"
      },
      {
        "file": "p117.jpg",
        "title": "eventreports"
      },
      {
        "file": "p118.jpg",
        "title": "EventCoords"
      },
      {
        "file": "p119.jpg",
        "title": "EventCoords"
      },
      {
        "file": "p120.jpg",
        "title": "EventCoords"
      },
      {
        "file": "p121.jpg",
        "title": "Event photos"
      },
      {
        "file": "p122.jpg",
        "title": "CTC&PARICHAY"
      },
      {
        "file": "p123.jpg",
        "title": "Event photos"
      },
      {
        "file": "p124.jpg",
        "title": "Event photos"
      }
    ]
  },
  {
    "id": "clubs",
    "name": "Club Reports",
    "section": "Club Reports",
    "lang": "en",
    "caption": "Clubs of PICT",
    "intro": "And finally, the many circles that make the campus turn.",
    "pages": [
      {
        "file": "p125.jpg",
        "title": "clubreport"
      },
      {
        "file": "p126.jpg",
        "title": "clubreport"
      },
      {
        "file": "p127.jpg",
        "title": "clubreport"
      },
      {
        "file": "p128.jpg",
        "title": "clubreport"
      },
      {
        "file": "p129.jpg",
        "title": "clubreport"
      },
      {
        "file": "p130.jpg",
        "title": "clubreport"
      },
      {
        "file": "p131.jpg",
        "title": "clubreport"
      },
      {
        "file": "p132.jpg",
        "title": "clubreport"
      },
      {
        "file": "p133.jpg",
        "title": "clubreport"
      },
      {
        "file": "p134.jpg",
        "title": "clubreport"
      },
      {
        "file": "p135.jpg",
        "title": "clubreport"
      },
      {
        "file": "p136.jpg",
        "title": "clubreport"
      },
      {
        "file": "p137.jpg",
        "title": "clubreport"
      },
      {
        "file": "p138.jpg",
        "title": "clubreport"
      },
      {
        "file": "p139.jpg",
        "title": "clubreport"
      },
      {
        "file": "p140.jpg",
        "title": "clubreport"
      },
      {
        "file": "p141.jpg",
        "title": "clubreport"
      },
      {
        "file": "p142.jpg",
        "title": "clubreport"
      },
      {
        "file": "p143.jpg",
        "title": "clubreport"
      },
      {
        "file": "p144.jpg",
        "title": "clubreport"
      },
      {
        "file": "p145.jpg",
        "title": "clubreport"
      },
      {
        "file": "p146.jpg",
        "title": "clubreport"
      },
      {
        "file": "p147.jpg",
        "title": "clubreport"
      },
      {
        "file": "p148.jpg",
        "title": "clubreport"
      },
      {
        "file": "p149.jpg",
        "title": "clubreport"
      },
      {
        "file": "p150.jpg",
        "title": "clubreport"
      },
      {
        "file": "p151.jpg",
        "title": "clubreport"
      },
      {
        "file": "p152.jpg",
        "title": "clubreport"
      },
      {
        "file": "p153.jpg",
        "title": "clubreport"
      },
      {
        "file": "p154.jpg",
        "title": "clubreport"
      }
    ]
  }
];
